fix: allow open source rpc example to compile
I'm assuming things work different with the internal build system, but the public release of dune needs this directive to output JavaScript. Also, without this, there's an error on use of any `Virtual_dom`:

```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Ojs referenced from /home/askvortsov/.opam/janestreet-stable/lib/virtual_dom/virtual_dom.cmxa(Virtual_dom__Js_map),
           /home/askvortsov/.opam/janestreet-stable/lib/virtual_dom/virtual_dom.cmxa(Virtual_dom__Raw),
           /home/askvortsov/.opam/janestreet-stable/lib/virtual_dom/virtual_dom.cmxa(Virtual_dom__Attr)
```

Signed-off-by: Alexander Skvortsov <sasha.skvortsov109@gmail.com>